# ---

# name: Checks

# on: [push]

# jobs: 
#   test-lint:
#     name: Test and Lint
#     runs-on : ubuntu-20.04
#     steps:
#       - name: Login TO DOcker Hub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.DOCKERHUB_USER}}
#           password: ${{ secrets.DOCKERHUB_TOKEN}}
#       - name: Checkoout
#         uses: actions/checkout@v2
#       - name: Test
#         run:  docker-compose run --rm app sh -c "python manage.py test"
#       - name: Lint
#         run:  docker-compose run --rm app sh -c "flake8"

name: Django Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

    - name: Set up Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

    - name: Build and run tests
      run: docker-compose run --rm app sh -c "python manage.py test"
    - name: Lint
      run:  docker-compose run --rm app sh -c "flake8"